name: Package and publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - rel/*
  pull_request:
    branches:
      - main
      - rel/*

jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - run: npm install -g @vscode/vsce

      - run: vsce package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: |
            **/*.vsix
            **/*.tgz
            !**/node_modules
