name: Package

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - rel/*
  pull_request:
    branches:
      - main
      - rel/*

jobs:
  package:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - run: npm install -g @vscode/vsce

      - run: vsce package --baseContentUrl https://github.com/juliencombattelli/vscode-android-init-language-syntax/blob/${{ github.sha }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-${{ github.sha }}
          path: android-init-language-syntax-*.vsix
